//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mzxxzy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class @class
    {
        public int id { get; set; }
        public Nullable<int> fid { get; set; }
        public string title { get; set; }
        public Nullable<int> disorder { get; set; }
    }
}
