//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mzxxzy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class relate
    {
        public int id { get; set; }
        public int know_id { get; set; }
        public int source_id { get; set; }
        public string isdelete { get; set; }
    }
}
