//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mzxxzy.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int user_id { get; set; }
        public string user_admin { get; set; }
        public string user_psw { get; set; }
        public string user_name { get; set; }
        public Nullable<System.DateTime> user_date { get; set; }
        public string user_tel { get; set; }
        public Nullable<short> rank { get; set; }
    }
}
